export const _chatUsers = [
  {
    chat_id: 0,
    users: [
      {
        id: 0,
        first_name: "Алена",
        second_name: "Иванова",
        display_name: "alena.i",
        login: "alena.i",
        email: "alena.i@email.com",
        phone: "89223332210",
        avatar: "/images/avatars/avatar-0.jpg",
        role: "user",
      },
      {
        id: 1,
        first_name: "Алексей",
        second_name: "Иванов",
        display_name: "Alex.I",
        login: "alex.i",
        email: "alex.i@email.com",
        phone: "89223332211",
        avatar: "/images/avatars/avatar-1.jpg",
        role: "user",
      },
      {
        id: 4,
        first_name: "Ирина",
        second_name: "Михайлова",
        display_name: "Irina.M",
        login: "irina.m",
        email: "irina.m@email.com",
        phone: "89223332214",
        avatar: "/images/avatars/avatar-4.jpg",
        role: "user",
      },
      {
        id: 6,
        first_name: "Мария",
        second_name: "Волкова",
        display_name: "Maria.V",
        login: "maria.v",
        email: "maria.v@email.com",
        phone: "89223332216",
        avatar: "/images/avatars/avatar-6.jpg",
        role: "user",
      },
      {
        id: 7,
        first_name: "Олег",
        second_name: "Семенов",
        display_name: "Oleg.S",
        login: "oleg.s",
        email: "oleg.s@email.com",
        phone: "89223332217",
        avatar: "/images/avatars/avatar-7.jpg",
        role: "user",
      },
      {
        id: 8,
        first_name: "Иванов",
        second_name: "Иван",
        display_name: "Ivanov.I",
        login: "ivanov.i",
        email: "ivanov.i@email.com",
        phone: "89223332218",
        avatar: "/images/avatars/avatar-8.jpg",
        role: "admin",
      },
    ],
  },
  {
    chat_id: 1,
    users: [
      {
        id: 0,
        first_name: "Алена",
        second_name: "Иванова",
        display_name: "alena.i",
        login: "alena.i",
        email: "alena.i@email.com",
        phone: "89223332210",
        avatar: "/images/avatars/avatar-0.jpg",
        role: "user",
      },
      {
        id: 1,
        first_name: "Алексей",
        second_name: "Иванов",
        display_name: "Alex.I",
        login: "alex.i",
        email: "alex.i@email.com",
        phone: "89223332211",
        avatar: "/images/avatars/avatar-1.jpg",
        role: "user",
      },
      {
        id: 3,
        first_name: "Анна",
        second_name: "Кузнецова",
        display_name: "Anna.K",
        login: "anna.k",
        email: "anna.k@email.com",
        phone: "89223332213",
        avatar: "/images/avatars/avatar-3.jpg",
        role: "user",
      },
      {
        id: 4,
        first_name: "Ирина",
        second_name: "Михайлова",
        display_name: "Irina.M",
        login: "irina.m",
        email: "irina.m@email.com",
        phone: "89223332214",
        avatar: "/images/avatars/avatar-4.jpg",
        role: "user",
      },
      {
        id: 6,
        first_name: "Мария",
        second_name: "Волкова",
        display_name: "Maria.V",
        login: "maria.v",
        email: "maria.v@email.com",
        phone: "89223332216",
        avatar: "/images/avatars/avatar-6.jpg",
        role: "user",
      },
      {
        id: 7,
        first_name: "Олег",
        second_name: "Семенов",
        display_name: "Oleg.S",
        login: "oleg.s",
        email: "oleg.s@email.com",
        phone: "89223332217",
        avatar: "/images/avatars/avatar-7.jpg",
        role: "user",
      },
      {
        id: 8,
        first_name: "Иванов",
        second_name: "Иван",
        display_name: "Ivanov.I",
        login: "ivanov.i",
        email: "ivanov.i@email.com",
        phone: "89223332218",
        avatar: "/images/avatars/avatar-8.jpg",
        role: "admin",
      },
    ],
  },
  {
    chat_id: 2,
    users: [
      {
        id: 2,
        first_name: "Артем",
        second_name: "Смирнов",
        display_name: "Artem.S",
        login: "artem.s",
        email: "artem.s@email.com",
        phone: "89223332212",
        avatar: "/images/avatars/avatar-2.jpg",
        role: "user",
      },
      {
        id: 3,
        first_name: "Анна",
        second_name: "Кузнецова",
        display_name: "Anna.K",
        login: "anna.k",
        email: "anna.k@email.com",
        phone: "89223332213",
        avatar: "/images/avatars/avatar-3.jpg",
        role: "user",
      },
      {
        id: 4,
        first_name: "Ирина",
        second_name: "Михайлова",
        display_name: "Irina.M",
        login: "irina.m",
        email: "irina.m@email.com",
        phone: "89223332214",
        avatar: "/images/avatars/avatar-4.jpg",
        role: "user",
      },
      {
        id: 7,
        first_name: "Олег",
        second_name: "Семенов",
        display_name: "Oleg.S",
        login: "oleg.s",
        email: "oleg.s@email.com",
        phone: "89223332217",
        avatar: "/images/avatars/avatar-7.jpg",
        role: "user",
      },
      {
        id: 8,
        first_name: "Иванов",
        second_name: "Иван",
        display_name: "Ivanov.I",
        login: "ivanov.i",
        email: "ivanov.i@email.com",
        phone: "89223332218",
        avatar: "/images/avatars/avatar-8.jpg",
        role: "admin",
      },
    ],
  },
];
